/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ArrowDown: THREE.Mesh
  }
  materials: {
    Black: THREE.MeshStandardMaterial
  }
}

export default function Model({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/arrowDown.glb') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.ArrowDown.geometry}
        material={materials.Black}
        rotation={[-Math.PI / 4, 0, 0]}
        scale={[0.22, 1, 1]}
      />
    </group>
  )
}

useGLTF.preload('/arrowDown.glb')
